name: Run Gradle on PRs
# Controls when the workflow will run
on:
  push:
    branches: [ hack-cicd ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: Setup Gradle and Build
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
        arguments: build
        build-root-directory: Examples/OneSignalDemo

    - name: Run Kotlin Linter
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
        arguments: ktlintStagingDebugCheck
        build-root-directory: Examples/OneSignalDemo

    - name: Run Unit Tests
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
        arguments: testStagingDebugUnitTest
        build-root-directory: Examples/OneSignalDemo

  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Setup NPM
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install App Center CLI
        run: npm install -g appcenter-cli