name: Run Gradle on PRs
# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    # Get the GitHub Actions repository keystore secret and add to project
    - name: Setup Android signing
      id: write_file
      uses: timheuer/base64-to-file@v1.1
      with:
        fileName: 'keystore.jks'
        fileDir: './Examples/OneSignalDemo/app/'
        encodedString: ${{ secrets.KEYSTORE }}

    - uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleRelease
        build-root-directory: Examples/OneSignalDemo
      env:
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    - name: Setup NPM
      if: startsWith(matrix.os,'ubuntu')
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install App Center CLI
      if: startsWith(matrix.os,'ubuntu')
      run: npm install -g appcenter-cli

    - name: Release to App Center
      if: startsWith(matrix.os,'ubuntu')
      run: appcenter distribute release --app OneSignal/Test-Android --file Examples/OneSignalDemo/app/build/outputs/apk/gms/release/app-gms-release.apk --token ${{secrets.APP_CENTER_TOKEN}} --group "Testers"
