name: Run Gradle on PRs
# Controls when the workflow will run
on:
  push:
    branches: [ try_signing_release ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    # Get the GitHub Actions repository keystore secret and add to project
    - name: Setup Android signing
      run: (echo ${{ secrets.KEYSTORE }} | base64 --decode) > ./Examples/OneSignalDemo/app/keystore.jks

    - name: Make gradlew executable
      working-directory: Examples/OneSignalDemo
      run: chmod +x ./gradlew

    - name: build prod
      run: ./gradlew app:bundleRelease
      working-directory: Examples/OneSignalDemo
      env:
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

    - name: List build contents
      run: ls -R Examples/OneSignalDemo/app

    # - name: Setup Gradle and Build
    #   uses: gradle/gradle-build-action@v2
    #   with:
    #     gradle-version: current
    #     arguments: build
    #     build-root-directory: Examples/OneSignalDemo

    # - uses: actions/upload-artifact@v3
    #   with:
    #     path: app

  # distribute:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:

  #     # Download build-artifacts
  #     - uses: actions/download-artifact@v3

  #     - name: Setup NPM
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'

  #     - name: Install App Center CLI
  #       run: npm install -g appcenter-cli