name: Run Gradle on PRs
# Controls when the workflow will run
on:
  push:
    branches: [ hack-cicd ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: Setup Gradle and Build
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
        arguments: build
        build-root-directory: Examples/OneSignalDemo

    - uses: actions/upload-artifact@v3
      with:
        path: app

  lint_and_test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    # Download build-artifacts
    - uses: actions/download-artifact@v3

    # # Check the code with ktlint
    # - name: Run Kotlin Linter
    #   uses: gradle/gradle-build-action@v2
    #   with:
    #     gradle-version: current
    #     build-root-directory: Examples/OneSignalDemo
    #     arguments: ktlintStagingDebugCheck

    # Check the code with Android linter
    - name: Run Android Linter
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
        build-root-directory: Examples/OneSignalDemo
        arguments: lintStagingDebug

    # Run unit tests
    - name: Run Unit Tests
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
        build-root-directory: Examples/OneSignalDemo
        arguments: testStagingDebugUnitTest

    # Assemble debug apk
    - name: Assemble Debug APK
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
        build-root-directory: Examples/OneSignalDemo
        arguments: assembleStagingDebug

    # Assemble debug test apk
    - name: Assemble Debug Test APK
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: current
        build-root-directory: Examples/OneSignalDemo
        arguments: assembleStagingDebugAndroidTest

  distribute:
    needs: lint_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      # Download build-artifacts
      - uses: actions/download-artifact@v3

      - name: Setup NPM
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install App Center CLI
        run: npm install -g appcenter-cli